//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSitem.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class faturaadres
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public faturaadres()
        {
            this.sepet = new HashSet<sepet>();
        }
    
        public int faturaadresid { get; set; }
        public Nullable<int> musterifkid { get; set; }
        public Nullable<int> ilfkid { get; set; }
        public Nullable<int> ilcefkid { get; set; }
        public string faturaadres1 { get; set; }
        public string faturakad { get; set; }
        public string faturasoyad { get; set; }
        public string faturatel { get; set; }
    
        public virtual il il { get; set; }
        public virtual ilce ilce { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sepet> sepet { get; set; }
        public virtual musteri musteri { get; set; }
    }
}
