//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSitem.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class websayfaEntities : DbContext
    {
        public websayfaEntities()
            : base("name=websayfaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<durum> durum { get; set; }
        public virtual DbSet<faturaadres> faturaadres { get; set; }
        public virtual DbSet<gonderimadres> gonderimadres { get; set; }
        public virtual DbSet<il> il { get; set; }
        public virtual DbSet<ilce> ilce { get; set; }
        public virtual DbSet<kategori> kategori { get; set; }
        public virtual DbSet<odemetipi> odemetipi { get; set; }
        public virtual DbSet<sepet> sepet { get; set; }
        public virtual DbSet<siparis> siparis { get; set; }
        public virtual DbSet<urun> urun { get; set; }
        public virtual DbSet<musteri> musteri { get; set; }
    }
}
