//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSitem.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sepet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sepet()
        {
            this.siparis = new HashSet<siparis>();
        }
    
        public int sepetid { get; set; }
        public Nullable<int> musterifkid { get; set; }
        public Nullable<int> urunfkid { get; set; }
        public Nullable<int> gonderimadresfkid { get; set; }
        public Nullable<int> faturaadresfkid { get; set; }
        public Nullable<int> urunadet { get; set; }
        public Nullable<int> fiyat { get; set; }
    
        public virtual faturaadres faturaadres { get; set; }
        public virtual gonderimadres gonderimadres { get; set; }
        public virtual urun urun { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siparis> siparis { get; set; }
        public virtual musteri musteri { get; set; }
    }
}
