//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSitem.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class siparis
    {
        public int siparisid { get; set; }
        public Nullable<int> sepetfkid { get; set; }
        public Nullable<int> toplamfiyat { get; set; }
        public Nullable<int> odemetipifkid { get; set; }
        public byte[] siparistarihi { get; set; }
    
        public virtual odemetipi odemetipi { get; set; }
        public virtual sepet sepet { get; set; }
    }
}
