//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSitem.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class siparis
    {
        public int siparisid { get; set; }
        public Nullable<int> musterifkid { get; set; }
        public Nullable<int> urunfkid { get; set; }
        public string urunadi { get; set; }
        public Nullable<int> urunbirimfiyati { get; set; }
        public Nullable<int> urunadet { get; set; }
        public string urunresmi { get; set; }
        public Nullable<int> toplamfiyat { get; set; }
        public Nullable<int> faturaadresfkid { get; set; }
        public Nullable<int> gonderimadresfkid { get; set; }
        public Nullable<int> odemetipifkid { get; set; }
        public Nullable<System.DateTime> siparistarihi { get; set; }
    
        public virtual faturaadres faturaadres { get; set; }
        public virtual gonderimadres gonderimadres { get; set; }
        public virtual musteri musteri { get; set; }
        public virtual odemetipi odemetipi { get; set; }
        public virtual urun urun { get; set; }
    }
}
